apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp
spec:
  replicas: 3
  selector:
    app: myjavaapp
    version: 2.6.2
  template:
    metadata:
      name: saikiran
      labels:
        app: myjavaapp
        version: 2.6.2
    spec:
      containers:
        - name: saikiran-container
          image: maha4iac/mahalogin:2
          ports:
            - containerPort: 8080

