apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp
spec:
  replicas: 2
  selector:
    app: myjavaapp
  template:
    metadata:
      name: saikiran
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: saikiran container
          image: bodasaikiran/myimage
          ports:
            - containerPort: 8080

