apiVersion: v1
kind: Service
metadata:
  name: sai-svc
  labels:
    app: myjavaapp
spec:
  type: NodePort
  selector:
    app: myjavaapp
  ports:
    - port: 8080
      NodePort: 30001
      Protocal: TCP
